<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Systema.De_Gestion.Academica.LN</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Systema.De Gestion.Academica.DAL\Systema.De Gestion.Academica.DAL.csproj" />
    <ProjectReference Include="..\Systema.De Gestion.Academica.NE\Systema.De Gestion.Academica.NE.csproj" />
  </ItemGroup>

</Project>
